# Generated by Django 5.1.7 on 2025-03-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('arms', 'Arms'), ('shoulders', 'Shoulders'), ('core', 'Core')], help_text='Primary muscle group targeted (e.g., chest, back, legs, arms, shoulders, core).', max_length=50)),
            ],
        ),
    ]
